removed unused #ignore comments in algebra.py
Got an 
```
error: Unused "type: ignore" comment  [unused-ignore]
```
when running mypy. Removed those comments.