Add py.typed as per PEP 561
This is so that other packages importing rdflib does not get warnings
like this:

```
$ python3.9 -m mypy --show-error-context --show-error-codes  test_rdflib.py
test_rdflib.py:1: error: Skipping analyzing "rdflib": found module but no type hints or library stubs  [import]
test_rdflib.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```