feat: v7 mkdocs (#3287)
* Pr/3143 (#3144)

* Start migrating the documentation from .rst sphynx to .md material for mkdocs. Add mkdocs.yml with proper configuration, enable automated generation of the doc API from the docstring, and start converting a few pages (index, getting started, developers) for demo.

* Add automated (opt-in) tests of all python codeblocks in the markdown docs using pytest-markdown-docs. Needed to comment 1 small test that seemingly should fail (AttributeError: DefinedNamespace like object has no attribute '_NS', indeed the DefinedNamespace class expect a _NS, so it makes sense it fails) but for some reason it was not properly failing when ran with regular pytest, but it fails with pytest-markdown-docs

* convert all documentations pages to markdown, convert all docstrings to markdown with google style, updated config for mkdocs (readthedocs, tox, task)
fixed https://github.com/RDFLib/rdflib/issues/3128

* delete files, dependencies and mentions related to sphinx

* uncomment test previously commented for experimenting with markdown codeblock testing

* update poetry lock

* blacked again

* ignore mypy errors

---------

Co-authored-by: Vincent Emonet <vincent.emonet@gmail.com>

* build: set mkdocs versions for rdflib v7 compatibility

* style: apply black formatting

* chore: mypy comments

* fix: mypy, ruff, and apply black formatting

* build: only test mkdocs build on python 3.11 and above

* build: update poetry lock

* build: fix python version constraint and add comment explaining why the python constraint for mkdocs deps

* build: update poetry lock

* chore: fix mypy and apply formatting

* build: set setuptools version constraints in tox.ini

* build: set berkeleydb version

* build: loosen berkeleydb constraint

---------

Co-authored-by: Nicholas Car <nick@kurrawong.net>
Co-authored-by: Vincent Emonet <vincent.emonet@gmail.com>